db:
  image: mysql
  environment:
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=TODO
    - MYSQL_ROOT_PASSWORD=root
web:
  image: eneskantepe/todo
  ports:
    - "80:8080"
  links:
    - db:localhost